// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wumaemzxmnlybsvvxdqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bWFlbXp4bW5seWJzdnZ4ZHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTY5MTUsImV4cCI6MjA1Nzk5MjkxNX0.-vgX9hUmkRXjM6ktdXP4WFzxTev7F8E39mpCHxpKYSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);